#### Import Python packages

In [6]:
import requests
import pandas as pd
import json
pd.set_option('display.max_columns', 500)
# Set your Alpha Vantage API Key
AV_API_Key='L5DZR3FLVQWA9BIX'

#### Search a ticker by keyword

In [3]:
search_keyword='meta'
url = 'https://www.alphavantage.co/query?function=SYMBOL_SEARCH&keywords={searchKeyword}&apikey={apiKey}'.format(apiKey=AV_API_Key, searchKeyword=search_keyword)
r_search = requests.get(url)
js_search = r_search.json()
df_search=pd.DataFrame(js_search)
display(df_search)

                                         bestMatches
0  {'1. symbol': 'META', '2. name': 'Meta Platfor...
1  {'1. symbol': 'METAX', '2. name': 'ALPS METIS ...
2  {'1. symbol': 'META.LON', '2. name': 'WisdomTr...
3  {'1. symbol': 'METEX.PAR', '2. name': 'Metabol...
4  {'1. symbol': 'METALCO.BSE', '2. name': 'METAL...
5  {'1. symbol': 'M16.FRK', '2. name': 'METACON A...
6  {'1. symbol': 'METALFORGE.BSE', '2. name': 'Me...
7  {'1. symbol': 'AIU', '2. name': 'Meta Data Ltd...
8  {'1. symbol': '7ME.FRK', '2. name': 'METabolic...
9  {'1. symbol': 'MAV.FRK', '2. name': 'METADVERT...

#### Add information based on GAFAM ticker

In [9]:
ticker_information=pd.DataFrame()
ticker_list=['GOOGL','AAPL', 'META', 'AMZN', 'MSFT']
for ticker in ticker_list :
    r_overview = requests.get('https://www.alphavantage.co/query?function=OVERVIEW&symbol={ticker}&apikey={apiKey}'.format(apiKey=AV_API_Key, ticker=ticker))
    js_overview=r_overview.json()
    df_overview=pd.json_normalize(js_overview)
    ticker_information=pd.concat([ticker_information, df_overview])
    display(ticker_information.head())

,Symbol,AssetType,Name,Description,CIK,Exchange,Currency,Country,Sector,Industry,Address,FiscalYearEnd,LatestQuarter,MarketCapitalization,EBITDA,PERatio,PEGRatio,BookValue,DividendPerShare,DividendYield,EPS,RevenuePerShareTTM,ProfitMargin,OperatingMarginTTM,ReturnOnAssetsTTM,ReturnOnEquityTTM,RevenueTTM,GrossProfitTTM,DilutedEPSTTM,QuarterlyEarningsGrowthYOY,QuarterlyRevenueGrowthYOY,AnalystTargetPrice,TrailingPE,ForwardPE,PriceToSalesRatioTTM,PriceToBookRatio,EVToRevenue,EVToEBITDA,Beta,52WeekHigh,52WeekLow,50DayMovingAverage,200DayMovingAverage,SharesOutstanding,DividendDate,ExDividendDate
0,GOOGL,Common Stock,Alphabet Inc Class A,Alphabet Inc. is an American multinational con...,1652044,NASDAQ,USD,USA,TECHNOLOGY,"SERVICES-COMPUTER PROGRAMMING, DATA PROCESSING...","1600 AMPHITHEATRE PARKWAY, MOUNTAIN VIEW, CA, US",December,2023-06-30,1744025158000,91374002000,29.18,1.34,21.15,0,0.0141,4.72,22.55,0.21,0.293,0.13,0.233,289531003000,156633000000,4.72,0.191,0.071,151.42,29.18,17.79,4.173,4.852,4.057,12.16,1.043,141.22,83.34,134.04,115.34,5933000000,None,None

,Symbol,AssetType,Name,Description,CIK,Exchange,Currency,Country,Sector,Industry,Address,FiscalYearEnd,LatestQuarter,MarketCapitalization,EBITDA,PERatio,PEGRatio,BookValue,DividendPerShare,DividendYield,EPS,RevenuePerShareTTM,ProfitMargin,OperatingMarginTTM,ReturnOnAssetsTTM,ReturnOnEquityTTM,RevenueTTM,GrossProfitTTM,DilutedEPSTTM,QuarterlyEarningsGrowthYOY,QuarterlyRevenueGrowthYOY,AnalystTargetPrice,TrailingPE,ForwardPE,PriceToSalesRatioTTM,PriceToBookRatio,EVToRevenue,EVToEBITDA,Beta,52WeekHigh,52WeekLow,50DayMovingAverage,200DayMovingAverage,SharesOutstanding,DividendDate,ExDividendDate
0,GOOGL,Common Stock,Alphabet Inc Class A,Alphabet Inc. is an American multinational con...,1652044,NASDAQ,USD,USA,TECHNOLOGY,"SERVICES-COMPUTER PROGRAMMING, DATA PROCESSING...","1600 AMPHITHEATRE PARKWAY, MOUNTAIN VIEW, CA, US",December,2023-06-30,1744025158000,91374002000,29.18,1.34,21.15,0,0.0141,4.72,22.55,0.21,0.293,0.13,0.233,289531003000,156633000000,4.72,0.191,0.071,151.42,29.18,17.79,4.173,4.852,4.057,12.16,1.043,141.22,83.34,134.04,115.34,5933000000,None,None
0,AAPL,Common Stock,Apple Inc,Apple Inc. is an American multinational techno...,320193,NASDAQ,USD,USA,TECHNOLOGY,ELECTRONIC COMPUTERS,"ONE INFINITE LOOP, CUPERTINO, CA, US",September,2023-06-30,2743176790000,123957002000,29.39,2.75,3.852,0.93,0.0055,5.97,24.22,0.247,0.281,0.209,1.601,383932989000,170782000000,5.97,0.05,-0.014,199.06,29.39,28.66,5.51,44.63,5.92,23.52,1.308,197.96,123.64,177.66,169.28,15634200000,2023-08-17,2023-08-11

,Symbol,AssetType,Name,Description,CIK,Exchange,Currency,Country,Sector,Industry,Address,FiscalYearEnd,LatestQuarter,MarketCapitalization,EBITDA,PERatio,PEGRatio,BookValue,DividendPerShare,DividendYield,EPS,RevenuePerShareTTM,ProfitMargin,OperatingMarginTTM,ReturnOnAssetsTTM,ReturnOnEquityTTM,RevenueTTM,GrossProfitTTM,DilutedEPSTTM,QuarterlyEarningsGrowthYOY,QuarterlyRevenueGrowthYOY,AnalystTargetPrice,TrailingPE,ForwardPE,PriceToSalesRatioTTM,PriceToBookRatio,EVToRevenue,EVToEBITDA,Beta,52WeekHigh,52WeekLow,50DayMovingAverage,200DayMovingAverage,SharesOutstanding,DividendDate,ExDividendDate
0,GOOGL,Common Stock,Alphabet Inc Class A,Alphabet Inc. is an American multinational con...,1652044,NASDAQ,USD,USA,TECHNOLOGY,"SERVICES-COMPUTER PROGRAMMING, DATA PROCESSING...","1600 AMPHITHEATRE PARKWAY, MOUNTAIN VIEW, CA, US",December,2023-06-30,1744025158000,91374002000,29.18,1.34,21.15,0,0.0141,4.72,22.55,0.21,0.293,0.13,0.233,289531003000,156633000000,4.72,0.191,0.071,151.42,29.18,17.79,4.173,4.852,4.057,12.16,1.043,141.22,83.34,134.04,115.34,5933000000,None,None
0,AAPL,Common Stock,Apple Inc,Apple Inc. is an American multinational techno...,320193,NASDAQ,USD,USA,TECHNOLOGY,ELECTRONIC COMPUTERS,"ONE INFINITE LOOP, CUPERTINO, CA, US",September,2023-06-30,2743176790000,123957002000,29.39,2.75,3.852,0.93,0.0055,5.97,24.22,0.247,0.281,0.209,1.601,383932989000,170782000000,5.97,0.05,-0.014,199.06,29.39,28.66,5.51,44.63,5.92,23.52,1.308,197.96,123.64,177.66,169.28,15634200000,2023-08-17,2023-08-11
0,META,Common Stock,Meta Platforms Inc.,"Meta Platforms, Inc. develops products that en...",1326801,NASDAQ,USD,USA,TECHNOLOGY,"SERVICES-COMPUTER PROGRAMMING, DATA PROCESSING...","1601 WILLOW ROAD, MENLO PARK, CA, US",December,2023-06-30,804910137000,44914000000,36.42,2.635,51.59,0,0,8.59,46.03,0.187,0.318,0.117,0.174,120524997000,92855000000,8.59,0.211,0.11,362.18,36.42,14.95,2.614,2.598,2.595,7.05,1.21,330.54,88.09,302.63,244.71,2222580000,None,None

,Symbol,AssetType,Name,Description,CIK,Exchange,Currency,Country,Sector,Industry,Address,FiscalYearEnd,LatestQuarter,MarketCapitalization,EBITDA,PERatio,PEGRatio,BookValue,DividendPerShare,DividendYield,EPS,RevenuePerShareTTM,ProfitMargin,OperatingMarginTTM,ReturnOnAssetsTTM,ReturnOnEquityTTM,RevenueTTM,GrossProfitTTM,DilutedEPSTTM,QuarterlyEarningsGrowthYOY,QuarterlyRevenueGrowthYOY,AnalystTargetPrice,TrailingPE,ForwardPE,PriceToSalesRatioTTM,PriceToBookRatio,EVToRevenue,EVToEBITDA,Beta,52WeekHigh,52WeekLow,50DayMovingAverage,200DayMovingAverage,SharesOutstanding,DividendDate,ExDividendDate
0,GOOGL,Common Stock,Alphabet Inc Class A,Alphabet Inc. is an American multinational con...,1652044,NASDAQ,USD,USA,TECHNOLOGY,"SERVICES-COMPUTER PROGRAMMING, DATA PROCESSING...","1600 AMPHITHEATRE PARKWAY, MOUNTAIN VIEW, CA, US",December,2023-06-30,1744025158000,91374002000,29.18,1.34,21.15,0,0.0141,4.72,22.55,0.21,0.293,0.13,0.233,289531003000,156633000000,4.72,0.191,0.071,151.42,29.18,17.79,4.173,4.852,4.057,12.16,1.043,141.22,83.34,134.04,115.34,5933000000,None,None
0,AAPL,Common Stock,Apple Inc,Apple Inc. is an American multinational techno...,320193,NASDAQ,USD,USA,TECHNOLOGY,ELECTRONIC COMPUTERS,"ONE INFINITE LOOP, CUPERTINO, CA, US",September,2023-06-30,2743176790000,123957002000,29.39,2.75,3.852,0.93,0.0055,5.97,24.22,0.247,0.281,0.209,1.601,383932989000,170782000000,5.97,0.05,-0.014,199.06,29.39,28.66,5.51,44.63,5.92,23.52,1.308,197.96,123.64,177.66,169.28,15634200000,2023-08-17,2023-08-11
0,META,Common Stock,Meta Platforms Inc.,"Meta Platforms, Inc. develops products that en...",1326801,NASDAQ,USD,USA,TECHNOLOGY,"SERVICES-COMPUTER PROGRAMMING, DATA PROCESSING...","1601 WILLOW ROAD, MENLO PARK, CA, US",December,2023-06-30,804910137000,44914000000,36.42,2.635,51.59,0,0,8.59,46.03,0.187,0.318,0.117,0.174,120524997000,92855000000,8.59,0.211,0.11,362.18,36.42,14.95,2.614,2.598,2.595,7.05,1.21,330.54,88.09,302.63,244.71,2222580000,None,None
0,AMZN,Common Stock,Amazon.com Inc,"Amazon.com, Inc. is an American multinational ...",1018724,NASDAQ,USD,USA,TRADE & SERVICES,RETAIL-CATALOG & MAIL-ORDER HOUSES,"410 TERRY AVENUE NORTH, SEATTLE, WA, US",December,2023-06-30,1324805521000,63431000000,101.9,11.85,16.35,0,0.0104,1.26,52.56,0.0243,0.0572,0.0247,0.0872,538046005000,225152000000,1.26,-0.986,0.108,170.3,101.9,43.86,1.797,6.61,1.948,19.3,1.188,145.86,81.43,133.69,116.17,10317800000,None,None

,Symbol,AssetType,Name,Description,CIK,Exchange,Currency,Country,Sector,Industry,Address,FiscalYearEnd,LatestQuarter,MarketCapitalization,EBITDA,PERatio,PEGRatio,BookValue,DividendPerShare,DividendYield,EPS,RevenuePerShareTTM,ProfitMargin,OperatingMarginTTM,ReturnOnAssetsTTM,ReturnOnEquityTTM,RevenueTTM,GrossProfitTTM,DilutedEPSTTM,QuarterlyEarningsGrowthYOY,QuarterlyRevenueGrowthYOY,AnalystTargetPrice,TrailingPE,ForwardPE,PriceToSalesRatioTTM,PriceToBookRatio,EVToRevenue,EVToEBITDA,Beta,52WeekHigh,52WeekLow,50DayMovingAverage,200DayMovingAverage,SharesOutstanding,DividendDate,ExDividendDate
0,GOOGL,Common Stock,Alphabet Inc Class A,Alphabet Inc. is an American multinational con...,1652044,NASDAQ,USD,USA,TECHNOLOGY,"SERVICES-COMPUTER PROGRAMMING, DATA PROCESSING...","1600 AMPHITHEATRE PARKWAY, MOUNTAIN VIEW, CA, US",December,2023-06-30,1744025158000,91374002000,29.18,1.34,21.15,0,0.0141,4.72,22.55,0.21,0.293,0.13,0.233,289531003000,156633000000,4.72,0.191,0.071,151.42,29.18,17.79,4.173,4.852,4.057,12.16,1.043,141.22,83.34,134.04,115.34,5933000000,None,None
0,AAPL,Common Stock,Apple Inc,Apple Inc. is an American multinational techno...,320193,NASDAQ,USD,USA,TECHNOLOGY,ELECTRONIC COMPUTERS,"ONE INFINITE LOOP, CUPERTINO, CA, US",September,2023-06-30,2743176790000,123957002000,29.39,2.75,3.852,0.93,0.0055,5.97,24.22,0.247,0.281,0.209,1.601,383932989000,170782000000,5.97,0.05,-0.014,199.06,29.39,28.66,5.51,44.63,5.92,23.52,1.308,197.96,123.64,177.66,169.28,15634200000,2023-08-17,2023-08-11
0,META,Common Stock,Meta Platforms Inc.,"Meta Platforms, Inc. develops products that en...",1326801,NASDAQ,USD,USA,TECHNOLOGY,"SERVICES-COMPUTER PROGRAMMING, DATA PROCESSING...","1601 WILLOW ROAD, MENLO PARK, CA, US",December,2023-06-30,804910137000,44914000000,36.42,2.635,51.59,0,0,8.59,46.03,0.187,0.318,0.117,0.174,120524997000,92855000000,8.59,0.211,0.11,362.18,36.42,14.95,2.614,2.598,2.595,7.05,1.21,330.54,88.09,302.63,244.71,2222580000,None,None
0,AMZN,Common Stock,Amazon.com Inc,"Amazon.com, Inc. is an American multinational ...",1018724,NASDAQ,USD,USA,TRADE & SERVICES,RETAIL-CATALOG & MAIL-ORDER HOUSES,"410 TERRY AVENUE NORTH, SEATTLE, WA, US",December,2023-06-30,1324805521000,63431000000,101.9,11.85,16.35,0,0.0104,1.26,52.56,0.0243,0.0572,0.0247,0.0872,538046005000,225152000000,1.26,-0.986,0.108,170.3,101.9,43.86,1.797,6.61,1.948,19.3,1.188,145.86,81.43,133.69,116.17,10317800000,None,None
0,MSFT,Common Stock,Microsoft Corporation,Microsoft Corporation is an American multinati...,789019,NASDAQ,USD,USA,TECHNOLOGY,SERVICES-PREPACKAGED SOFTWARE,"ONE MICROSOFT WAY, REDMOND, WA, US",June,2023-06-30,2452637876000,102022996000,34.14,2.275,27.75,2.72,0.0091,9.67,28.46,0.342,0.411,0.142,0.388,211914998000,135620000000,9.67,0.202,0.083,392.34,34.14,27.03,9.14,11.05,9.21,18.55,0.899,366.01,211.39,325.09,301.55,7429760000,2023-12-14,2023-11-15

#### Get GAFAM daily stock market

In [10]:
ticker_time_series=pd.DataFrame()
ticker_metadata=pd.DataFrame()
ticker_list=['GOOGL','AAPL', 'META', 'AMZN', 'MSFT']
for ticker in ticker_list :
    r_stock = requests.get('https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&outputsize=full&symbol={ticker}&apikey={apiKey}'.format(apiKey=AV_API_Key, ticker=ticker))
    js_stock = r_stock.json()
    # Ticker time series to DataFrame
    df_time_series=pd.DataFrame(js_stock['Time Series (Daily)'])
    df_time_series['Ticker']=ticker
    ticker_time_series=pd.concat([ticker_time_series, df_time_series])
    # Ticker metadata to DataFrame
    df_metadata=pd.json_normalize(js_stock['Meta Data'])
    df_metadata['Ticker']=ticker
    ticker_metadata=pd.concat([ticker_metadata, df_metadata])
display(ticker_time_series.head())
display(ticker_metadata.head())

,2023-10-19,2023-10-18,2023-10-17,2023-10-16,2023-10-13,2023-10-12,2023-10-11,2023-10-10,2023-10-09,2023-10-06,2023-10-05,2023-10-04,2023-10-03,2023-10-02,2023-09-29,2023-09-28,2023-09-27,2023-09-26,2023-09-25,2023-09-22,2023-09-21,2023-09-20,2023-09-19,2023-09-18,2023-09-15,2023-09-14,2023-09-13,2023-09-12,2023-09-11,2023-09-08,2023-09-07,2023-09-06,2023-09-05,2023-09-01,2023-08-31,2023-08-30,2023-08-29,2023-08-28,2023-08-25,2023-08-24,2023-08-23,2023-08-22,2023-08-21,2023-08-18,2023-08-17,2023-08-16,2023-08-15,2023-08-14,2023-08-11,2023-08-10,2023-08-09,2023-08-08,2023-08-07,2023-08-04,2023-08-03,2023-08-02,2023-08-01,2023-07-31,2023-07-28,2023-07-27,2023-07-26,2023-07-25,2023-07-24,2023-07-21,2023-07-20,2023-07-19,2023-07-18,2023-07-17,2023-07-14,2023-07-13,2023-07-12,2023-07-11,2023-07-10,2023-07-07,2023-07-06,2023-07-05,2023-07-03,2023-06-30,2023-06-29,2023-06-28,2023-06-27,2023-06-26,2023-06-23,2023-06-22,2023-06-21,2023-06-20,2023-06-16,2023-06-15,2023-06-14,2023-06-13,2023-06-12,2023-06-09,2023-06-08,2023-06-07,2023-06-06,2023-06-05,2023-06-02,2023-06-01,2023-05-31,2023-05-30,2023-05-26,2023-05-25,2023-05-24,2023-05-23,2023-05-22,2023-05-19,2023-05-18,2023-05-17,2023-05-16,2023-05-15,2023-05-12,2023-05-11,2023-05-10,2023-05-09,2023-05-08,2023-05-05,2023-05-04,2023-05-03,2023-05-02,2023-05-01,2023-04-28,2023-04-27,2023-04-26,2023-04-25,2023-04-24,2023-04-21,2023-04-20,2023-04-19,2023-04-18,2023-04-17,2023-04-14,2023-04-13,2023-04-12,2023-04-11,2023-04-10,2023-04-06,2023-04-05,2023-04-04,2023-04-03,2023-03-31,2023-03-30,2023-03-29,2023-03-28,2023-03-27,2023-03-24,2023-03-23,2023-03-22,2023-03-21,2023-03-20,2023-03-17,2023-03-16,2023-03-15,2023-03-14,2023-03-13,2023-03-10,2023-03-09,2023-03-08,2023-03-07,2023-03-06,2023-03-03,2023-03-02,2023-03-01,2023-02-28,2023-02-27,2023-02-24,2023-02-23,2023-02-22,2023-02-21,2023-02-17,2023-02-16,2023-02-15,2023-02-14,2023-02-13,2023-02-10,2023-02-09,2023-02-08,2023-02-07,2023-02-06,2023-02-03,2023-02-02,2023-02-01,2023-01-31,2023-01-30,2023-01-27,2023-01-26,2023-01-25,2023-01-24,2023-01-23,2023-01-20,2023-01-19,2023-01-18,2023-01-17,2023-01-13,2023-01-12,2023-01-11,2023-01-10,2023-01-09,2023-01-06,2023-01-05,2023-01-04,2023-01-03,2022-12-30,2022-12-29,2022-12-28,2022-12-27,2022-12-23,2022-12-22,2022-12-21,2022-12-20,2022-12-19,2022-12-16,2022-12-15,2022-12-14,2022-12-13,2022-12-12,2022-12-09,2022-12-08,2022-12-07,2022-12-06,2022-12-05,2022-12-02,2022-12-01,2022-11-30,2022-11-29,2022-11-28,2022-11-25,2022-11-23,2022-11-22,2022-11-21,2022-11-18,2022-11-17,2022-11-16,2022-11-15,2022-11-14,2022-11-11,2022-11-10,2022-11-09,2022-11-08,2022-11-07,2022-11-04,2022-11-03,2022-11-02,2022-11-01,2022-10-31,2022-10-28,2022-10-27,2022-10-26,2022-10-25,2022-10-24,2022-10-21,...,2000-10-25,2000-10-24,2000-10-23,2000-10-20,2000-10-19,2000-10-18,2000-10-17,2000-10-16,2000-10-13,2000-10-12,2000-10-11,2000-10-10,2000-10-09,2000-10-06,2000-10-05,2000-10-04,2000-10-03,2000-10-02,2000-09-29,2000-09-28,2000-09-27,2000-09-26,2000-09-25,2000-09-22,2000-09-21,2000-09-20,2000-09-19,2000-09-18,2000-09-15,2000-09-14,2000-09-13,2000-09-12,2000-09-11,2000-09-08,2000-09-07,2000-09-06,2000-09-05,2000-09-01,2000-08-31,2000-08-30,2000-08-29,2000-08-28,2000-08-25,2000-08-24,2000-08-23,2000-08-22,2000-08-21,2000-08-18,2000-08-17,2000-08-16,2000-08-15,2000-08-14,2000-08-11,2000-08-10,2000-08-09,2000-08-08,2000-08-07,2000-08-04,2000-08-03,2000-08-02,2000-08-01,2000-07-31,2000-07-28,2000-07-27,2000-07-26,2000-07-25,2000-07-24,2000-07-21,2000-07-20,2000-07-19,2000-07-18,2000-07-17,2000-07-14,2000-07-13,2000-07-12,2000-07-11,2000-07-10,2000-07-07,2000-07-06,2000-07-05,2000-07-03,2000-06-30,2000-06-29,2000-06-28,2000-06-27,2000-06-26,2000-06-23,2000-06-22,2000-06-21,2000-06-20,2000-06-19,2000-06-16,2000-06-15,2000-06-14,2000-06-13,2000-06-12,2000-06-09,2000-06-08,2000-06-07,2000-06-06,2000-06-05,2000-06-02,2000-06-01,2000-05-31,2000-05-30,2000-05-26,2000-05-25,2000-05-24,2000-05-23,2000-05-22,2000-05-19,2000-05-18,2000-05-17,2000-05-16,2000-05-15,2000-05-12,2000-05-11,2000-05-10,2000-05-09,2000-05-08,2000-05-05,2000-05-04,2000-05-03,2000-05-02,2000-05-01,2000-04-28,2000-04-27,2000-04-26,2000-04-25,2000-04-24,2000-04-20,2000-04-19,2000-04-18,2000-04-17,2000-04-14,2000-04-13,2000-04-12,2000-04-11,2000-04-10,2000-04-07,2000-04-06,2000-04-05,2000-04-04,2000-04-03,2000-03-31,2000-03-30,2000-03-29,2000-03-28,2000-03-27,2000-03-24,2000-03-23,2000-03-22,2000-03-21,2000-03-20,2000-03-17,2000-03-16,2000-03-15,2000-03-14,2000-03-13,2000-03-10,2000-03-09,2000-03-08,2000-03-07,2000-03-06,2000-03-03,2000-03-02,2000-03-01,2000-02-29,2000-02-28,2000-02-25,2000-02-24,2000-02-23,2000-02-22,2000-02-18,2000-02-17,2000-02-16,2000-02-15,2000-02-14,2000-02-11,2000-02-10,2000-02-09,2000-02-08,2000-02-07,2000-02-04,2000-02-03,2000-02-02,2000-02-01,2000-01-31,2000-01-28,2000-01-27,2000-01-26,2000-01-25,2000-01-24,2000-01-21,2000-01-20,2000-01-19,2000-01-18,2000-01-14,2000-01-13,2000-01-12,2000-01-11,2000-01-10,2000-01-07,2000-01-06,2000-01-05,2000-01-04,2000-01-03,1999-12-31,1999-12-30,1999-12-29,1999-12-28,1999-12-27,1999-12-23,1999-12-22,1999-12-21,1999-12-20,1999-12-17,1999-12-16,1999-12-15,1999-12-14,1999-12-13,1999-12-10,1999-12-09,1999-12-08,1999-12-07,1999-12-06,1999-12-03,1999-12-02,1999-12-01,1999-11-30,1999-11-29,1999-11-26,1999-11-24,1999-11-23,1999-11-22,1999-11-19,1999-11-18,1999-11-17,1999-11-16,1999-11-15,1999-11-12,1999-11-11,1999-11-10,1999-11-09,1999-11-08,1999-11-05,1999-11-04,1999-11-03,1999-11-02,1999-11-01
1. open,138.5000,139.4450,138.6300,138.1700,139.3800,141.0500,138.5800,138.5000,136.9400,134.0100,135.0700,132.7900,133.9400,131.2100,133.2800,129.8400,128.5700,129.7700,129.8300,130.7600,131.4400,138.0800,137.4200,136.6100,137.9800,137.6000,135.0900,136.2600,136.5400,134.9100,133.5900,136.0200,135.4400,137.4550,136.0100,134.7800,132.2400,131.3100,129.5400,133.9500,130.1800,128.5100,127.1750,128.5100,129.8000,128.7000,131.1000,129.3900,128.6600,131.3200,131.6600,130.6200,129.1600,129.2800,127.9700,129.4500,130.7750,132.7300,130.7800,131.6700,130.0700,121.3600,121.6600,120.6200,121.4200,124.6000,124.6000,125.9400,124.8000,120.9300,118.8000,116.2900,118.3000,120.1000,119.7950,119.2400,119.2400,120.1700,119.2400,117.0900,117.0800,120.7600,121.3800,120.0000,122.4000,122.9300,125.9300,123.1400,123.1000,124.9800,122.7850,122.2500,122.2250,126.9700,126.0100,124.0100,123.9900,122.8150,122.7500,125.6400,123.1700,124.5200,121.1200,124.1600,122.9400,123.5500,120.9500,119.6100,116.4900,116.1100,116.6800,115.3950,107.9700,108.3900,105.1800,104.8200,105.4850,105.5300,107.1400,106.8400,107.0400,104.4500,104.9200,105.8250,105.4900,105.4700,103.9100,103.5800,106.4900,104.6580,106.8900,105.8400,106.5800,106.5500,106.9800,105.2600,105.7800,104.3300,102.3900,101.3000,100.9100,102.2800,102.4400,104.6150,104.9900,105.0600,104.2700,101.2500,100.1200,100.2600,96.2000,93.2200,92.5600,90.0900,92.1700,94.0500,94.1200,94.9800,94.0150,92.4800,89.6600,89.9800,89.3300,89.8700,89.4400,91.9200,91.7000,93.0000,94.8500,95.3700,94.4900,94.4300,94.7400,95.4500,100.0000,102.0500,103.2200,102.4000,102.9300,105.8000,98.7100,96.8700,97.4800,97.3100,96.5000,95.5700,98.1000,97.9500,95.1000,90.7200,92.1400,92.0600,90.8500,91.4800,89.1800,85.9800,88.3600,86.7900,87.4700,90.3500,89.5850,86.9800,86.6200,86.9800,88.7950,87.1100,88.1600,89.0800,88.1100,90.2550,90.7600,93.1300,95.2000,97.7600,92.7100,93.7700,95.3800,96.4100,99.3000,99.4000,99.0500,101.0200,94.8200,95.7300,97.0363,98.2400,97.0900,95.9500,97.2900,98.7700,96.9700,97.9000,98.2600,95.0900,94.6900,92.2500,88.4500,88.9000,87.2800,85.4000,86.3200,90.9400,95.4500,95.4200,92.2700,94.5200,96.4300,102.9000,101.8000,97.8450,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2. high,139.6600,140.7200,139.9000,139.6300,140.0000,141.2200,141.1100,139.7200,138.9400,138.1550,135.4900,135.5700,134.2600,134.4200,134.0500,133.3000,130.8950,130.3645,131.1700,132.0250,132.2300,138.0800,138.4100,139.1600,138.5200,138.6950,136.9000,136.8701,137.4800,136.6600,135.5800,136.5299,136.4200,137.4550,138.0000,136.2750,136.5700,132.5400,130.7600,134.2500,133.4100,130.2780,128.7250,129.2500,131.9900,130.2809,131.4200,131.3700,129.9300,132.0500,132.0400,131.5100,131.6100,131.5100,129.3850,130.0900,132.6300,133.5250,133.7400,133.2400,130.9800,123.1450,123.0000,120.9900,124.0900,125.1800,124.6800,127.0999,126.7750,124.8300,120.3300,117.7100,118.3050,121.0500,120.3000,122.6100,120.1900,121.0800,120.0600,120.3900,119.0800,122.0000,122.7879,123.2400,122.6600,124.5700,126.1080,125.4600,124.0500,125.1600,124.0500,123.7550,123.2250,129.0400,128.2900,127.4300,126.1500,124.4200,124.0601,125.6600,125.2600,125.3200,121.9100,124.6250,126.4300,125.9700,123.3100,121.6700,120.7500,118.4800,118.0300,117.9200,112.9400,110.1500,107.9600,105.8800,105.6000,107.4900,107.2000,107.9900,107.3500,108.3700,106.3500,106.6900,106.6300,106.0000,106.2500,104.9800,106.5400,106.1600,108.9400,107.4900,106.7500,106.7300,107.5900,109.1700,106.1000,105.5800,104.5300,103.8900,101.1550,102.4900,102.4500,104.7600,105.4900,106.3000,106.5900,105.1000,101.7500,102.8350,101.1900,96.9300,94.3600,92.5700,92.7900,95.5300,95.9550,95.6700,95.9700,93.7300,92.2750,91.0300,91.2300,90.1600,89.8900,91.9400,92.1100,93.1000,95.5599,97.6800,97.1200,94.8450,95.2000,96.7500,100.0300,103.1400,108.1800,104.3600,107.8100,107.8500,101.1900,98.8800,98.2900,100.3200,97.5700,96.1620,99.6100,100.0400,98.3000,93.6050,92.7999,92.2500,92.1900,91.8700,91.6000,88.6700,90.0500,87.6900,87.5700,90.6500,91.0500,88.3000,88.8450,88.0400,88.9400,89.5450,88.5400,90.2200,89.1750,90.5600,91.3300,93.6400,96.8700,99.5300,93.5600,94.2600,95.5800,96.8811,99.7800,101.3800,100.7700,102.2500,101.0400,96.1200,97.5800,98.6400,98.7600,97.2200,98.4000,98.9000,99.2800,99.6375,100.1400,96.7900,96.9300,94.3900,89.4350,90.3200,88.9000,86.6400,86.5200,91.1800,96.0300,96.0300,96.5500,95.4300,98.3100,104.8200,102.7500,101.3100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3. low,137.3800,137.3800,137.1800,137.9900,136.6150,138.2600,138.5800,137.3300,135.6100,134.0100,133.4500,132.5300,131.8400,131.1700,130.3600,129.7900,128.5700,127.2200,128.9600,129.6000,130.0700,133.6200,136.6200,136.6100,136.4800,136.2400,134.1500,135.1900,135.7850,134.8500,132.9500,133.6650,134.5801,134.8500,135.7900,134.0700,132.2400,130.1400,127.2500,129.5700,129.8700,128.3200,126.5600,126.3824,129.2900,127.8650,129.2800,128.9600,128.1700,129.4500,129.0000,129.5450,129.0200,127.9100,127.4200,127.5600,130.6800,131.7750,130.5700,128.7900,128.3200,121.0200,120.9800,118.7300,118.2200,121.8000,122.9600,124.1950,123.4900,120.4500,118.4145,115.3500,116.1350,119.4000,118.4000,119.2300,118.8182,119.6900,118.2950,116.8500,116.1000,118.2650,121.0600,118.8300,120.1000,122.1400,123.2800,122.4000,121.4500,123.1800,121.6600,121.9100,121.2400,122.1200,125.3600,123.8400,123.7600,122.6200,122.5000,122.0000,122.4500,121.9600,119.8600,122.2104,122.7400,122.1500,120.8300,118.8900,116.4300,116.0100,116.1100,114.4100,107.9300,107.1900,105.1600,104.1100,103.9700,104.9600,103.7100,106.8200,105.0900,103.5400,102.6300,103.8400,104.7000,104.7800,103.8684,103.0700,104.0700,104.5200,106.8400,105.8400,104.3400,104.6800,105.1200,104.3300,103.6600,104.0400,101.9300,101.0400,99.7800,100.6500,99.7400,101.9273,103.8400,104.4600,103.3300,101.2200,99.8700,100.1000,95.5000,92.6400,92.4400,89.4200,90.3950,91.9000,94.0000,93.5300,94.0000,92.4500,89.5900,89.6700,89.3200,89.3350,88.5750,89.7600,90.6100,91.7200,93.2100,94.7400,94.1500,92.2600,93.8400,94.2500,93.6300,98.0350,103.1200,101.8800,102.5800,105.6100,97.5800,96.8200,96.3950,97.3100,95.3800,93.7600,97.2000,97.5000,95.0200,90.6300,90.6400,90.0500,90.1299,89.7500,89.0100,85.8300,87.8600,84.8600,85.9000,87.2710,88.5200,86.5700,86.6100,85.9400,87.0100,87.0700,86.3200,88.3200,87.4401,88.2100,89.5200,90.0100,93.6000,95.0300,91.6100,92.7500,93.4500,94.7150,96.4200,99.0000,98.9000,100.2500,94.4200,94.1100,95.6100,97.4000,97.0900,94.0500,95.3550,96.3700,96.7900,97.6400,96.7100,94.5100,93.9200,91.6100,87.2800,87.5901,86.8500,83.7100,83.3400,86.8800,90.3700,93.9800,92.1300,91.8000,94.6900,102.7200,99.9800,97.7200,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4. close,137.7500,137.9600,139.7200,139.0950,137.3600,138.9700,140.5500,138.0600,138.4200,137.5800,135.0700,135.2400,132.4300,134.1700,130.8600,132.3100,130.5400,128.5650,131.1100,130.2500,130.4400,133.7400,138.0400,138.2100,137.4000,138.1000,136.7100,135.3400,136.9200,136.3800,135.2600,134.4600,135.7700,135.6600,136.1700,135.8800,134.5700,131.0100,129.8800,129.7800,132.3700,129.0800,128.3700,127.4600,129.9200,128.7000,129.7800,131.3300,129.5600,129.6900,129.6600,131.4000,131.5300,128.1100,128.4500,128.3800,131.5500,132.7200,132.5800,129.4000,129.2700,122.2100,121.5300,120.0200,119.2000,122.0300,123.7600,124.6500,125.4200,124.5400,118.9300,117.1400,116.4500,119.4800,120.1100,121.7500,119.9000,119.7000,119.1000,120.1800,118.3300,118.3400,122.3400,123.1500,120.5500,123.1000,123.5300,125.0900,123.6700,123.8300,123.6400,122.2300,122.1400,122.5000,127.3100,126.0100,124.6700,123.7200,122.8700,123.6700,124.6100,123.4800,120.9000,122.5600,125.0500,122.7600,122.8300,120.8400,119.5100,116.5100,117.5100,116.5700,111.7500,107.3500,107.7700,105.5700,104.6900,105.4100,105.3200,107.2000,107.3400,107.5900,103.7100,103.8500,105.9700,105.4100,105.2900,104.1800,104.5000,105.9700,108.8700,107.4300,104.6400,105.3500,106.4400,108.4200,104.4700,104.7200,104.3600,103.7300,100.8900,101.3900,101.0300,102.4600,105.4400,105.6000,103.3700,104.9200,101.2200,101.6200,100.3200,96.1100,93.9700,91.1100,90.6300,92.3200,94.2500,93.8600,95.1300,93.6500,92.0000,90.3600,90.0600,89.8700,89.1300,90.8900,91.6500,91.7900,94.3500,95.5100,96.9400,94.6800,94.6100,94.5700,95.0100,99.3700,107.6400,102.9000,104.7800,107.7400,100.4300,98.8400,96.9400,99.3700,97.5200,95.2200,97.7000,99.7900,98.0200,93.0500,91.1200,91.2900,92.1200,91.1300,91.5200,88.4200,88.0200,87.3400,86.2000,88.0800,89.1200,88.2300,88.4500,86.0200,87.3900,89.2300,87.7600,89.5800,89.0200,88.4400,90.2600,90.8600,95.0700,95.6300,93.3100,92.8300,93.7100,94.9400,96.9800,99.4800,100.4400,100.9900,100.9900,95.1900,96.0500,97.4600,98.4600,97.0500,95.6000,97.4300,98.3600,98.8500,98.4400,95.7000,96.4100,93.9400,87.3200,88.9000,88.4900,86.5800,83.4300,86.9700,90.4700,94.5100,96.2900,92.2200,94.9300,104.4800,102.5200,101.1300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,1. Information,2. Symbol,3. Last Refreshed,4. Output Size,5. Time Zone,Ticker
0,"Daily Prices (open, high, low, close) and Volumes",GOOGL,2023-10-19,Full size,US/Eastern,GOOGL
0,"Daily Prices (open, high, low, close) and Volumes",AAPL,2023-10-19,Full size,US/Eastern,AAPL
0,"Daily Prices (open, high, low, close) and Volumes",META,2023-10-19,Full size,US/Eastern,META
0,"Daily Prices (open, high, low, close) and Volumes",AMZN,2023-10-19,Full size,US/Eastern,AMZN
0,"Daily Prices (open, high, low, close) and Volumes",MSFT,2023-10-19,Full size,US/Eastern,MSFT

#### Reset index and melt DataFrame

In [12]:
ticker_time_series=ticker_time_series.reset_index().rename({'index':'Value_type'}, axis=1)
lg_ticker_ts = ticker_time_series.melt(id_vars=['Ticker','Value_type'])
display(lg_ticker_ts.head())

  Ticker Value_type    variable     value
0  GOOGL    1. open  2023-10-19  138.5000
1  GOOGL    2. high  2023-10-19  139.6600
2  GOOGL     3. low  2023-10-19  137.3800
3  GOOGL   4. close  2023-10-19  137.7500
4  GOOGL  5. volume  2023-10-19  26066011

In [16]:
lg_ticker_ts

       Ticker Value_type    variable     value
0       GOOGL    1. open  2023-10-19  138.5000
1       GOOGL    2. high  2023-10-19  139.6600
2       GOOGL     3. low  2023-10-19  137.3800
3       GOOGL   4. close  2023-10-19  137.7500
4       GOOGL  5. volume  2023-10-19  26066011
...       ...        ...         ...       ...
150770   MSFT    1. open  1999-11-01   93.2500
150771   MSFT    2. high  1999-11-01   94.1900
150772   MSFT     3. low  1999-11-01   92.1200
150773   MSFT   4. close  1999-11-01   92.3700
150774   MSFT  5. volume  1999-11-01  26630600

[150775 rows x 4 columns]

In [20]:
lg_ticker_ts[['Ticker', "variable"]].value_counts()

Ticker  variable
AAPL    1999-11-01    5
META    2007-10-24    5
        2007-11-09    5
        2007-11-08    5
        2007-11-07    5
                     ..
AMZN    2015-10-19    5
        2015-10-16    5
        2015-10-15    5
        2015-10-14    5
MSFT    2023-10-19    5
Name: count, Length: 30155, dtype: int64